# models recipes
AMOUNT_MAX = 1000
AMOUNT_MIN = 1
TITLE_MAX_LENGTH = 256
NAME_MAX_LENGTH = 256
SLUG_MAX_LENGTH = 50
UNIT_MAX_LENGTH = 10
COOKING_MAX_TIME = 1440
COOKING_MIN_TIME = 1
SHORT_LINK_SIZE = 3
ORIGINAL_URL_SIZE = 256

# models users
EMAIL_MAX_LENGTH = 254
USER_MAX_LENGTH = 150

# settings
PAGE_SIZE_MAX = 6
