version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: alexeybykov112/foodgram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media

  frontend:
    image: alexeybykov112/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static

  nginx:
    image: alexeybykov112/foodgram+_gateway
    env_file: .env
    ports:
      - "8000:80"
    volumes:
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static:/static
      - media:/media
